// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pantyukhov/imageresizeserver/services"
	"github.com/pantyukhov/imageresizeserver/transport"
)

// Injectors from wire.go:

func InitializeTransport() transport.Transport {
	fileService := services.NewFileService()
	fileHandler := transport.NewFileHandler(fileService)
	transportTransport := transport.NewTransport(fileHandler)
	return transportTransport
}
